baseURL = 'http://nitmic.club.nitech.ac.jp/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'

# theme = "mainroad"

baseurl = "/"
title = "NITMic" # NITMicに変更
languageCode = "ja" # jaに変更
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

# HUGOの書き出し先ファイルを設定
# publishDir = "docs"


#日本語用の.Summary設定
hasCJKLanguage = true 
summaryLength = 130

[taxonomies]
  author = "authors"
  member = "members"
  tag = "tags"
  category = "categories"

[Author]
  name = "John Doe"
  bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "img/avatar.png"

[Params]
  description = "名古屋工業大学コンピュータ倶楽部NITMic公式ホームページ" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = false # Show "Read more" button in list if true
  authorbox = false
  pager = true
  post_meta = ["date","author","categories"] # Order of post meta information
  highlightColor = "#ff9305" # ハイライトカラーを変更
  customCSS = ["css/style.css"]

[Params.logo]
  subtitle = "名古屋工業大学コンピュータ倶楽部" # Logo subtitle
  image = "logo/logo.png"

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = [ "recent", "categories", "social" ,"taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  twitter = "nitmic_twi"
  github = "nitmic-git"
